import fs from "fs";
import path from "path";

export function writeBackendEnv(params: {
  backendPath: string;
  dbUser?: string;
  dbPass?: string;
  dbName?: string;
}) {
  const {
    backendPath,
    dbUser = "startup",
    dbPass = "startup",
    dbName = "startupdb",
  } = params;

  // Inside docker network, DB hostname is "db"
  const envText =
`# Auto-generated by platform-api 
DB_HOST=db
DB_PORT=5432
DB_USER=${dbUser}
DB_PASS=${dbPass}
DB_NAME=${dbName}
PORT=4000
DATABASE_URL="postgresql://${dbUser}:${dbPass}@db:5432/${dbName}?schema=public"
JWT_SECRET=supersecret
ADMIN_EMAIL=admin@example.com
ADMIN_PASSWORD=admin123
`;

  fs.writeFileSync(path.join(backendPath, ".env"), envText, "ascii");
}
