import fs from "fs";
import path from "path";

export function writeSandboxEnv(params: {
  sandboxPath: string;
  webPort: number;
  dbPort: number;
  n8nPort: number;
  backendPort: number;

  startupDbUser?: string;
  startupDbPass?: string;
  startupDbName?: string;

  n8nUser?: string;
  n8nPass?: string;

  n8nApiKey?: string;
  platformApiPort?: number;
  ollamaPort?: number;
}) {
  const {
    sandboxPath,
    webPort,
    dbPort,
    n8nPort,
    backendPort,

    startupDbUser = "startup",
    startupDbPass = "startup",
    startupDbName = "startupdb",

    n8nUser = "admin",
    n8nPass = "admin123",

    n8nApiKey = "dev-api-key-123",
    platformApiPort = 5050,
    ollamaPort = 11434,
  } = params;

  const envText =
    `# Auto-generated by platform-api
  WEB_PORT=${webPort}
  DB_PORT=${dbPort}
  N8N_PORT=${n8nPort}

  POSTGRES_USER=${startupDbUser}
  POSTGRES_PASSWORD=${startupDbPass}
  POSTGRES_DB=${startupDbName}
  POSTGRES_DB_N8N=n8ndb
  BACKEND_PORT=${backendPort}
  BACKEND_INTERNAL_URL=http://backend:${backendPort}

  # n8n basic auth (UI)
  N8N_BASIC_AUTH_ACTIVE=true
  N8N_BASIC_AUTH_USER=${n8nUser}
  N8N_BASIC_AUTH_PASSWORD=${n8nPass}

  # n8n owner bootstrap (for /rest/owner/setup)
  N8N_OWNER_EMAIL=admin@example.com
  N8N_OWNER_FIRST_NAME=Admin
  N8N_OWNER_LAST_NAME=Startup
  N8N_OWNER_PASSWORD=Admin12345

  # n8n REST API access
  N8N_API_KEY=${n8nApiKey}
  N8N_PUBLIC_API_DISABLED=false

  N8N_DIAGNOSTICS_ENABLED=false
  N8N_PERSONALIZATION_ENABLED=false
  PLATFORM_API_URL=http://host.docker.internal:${platformApiPort}
  OLLAMA_URL=http://host.docker.internal:${ollamaPort}/api/generate
  `;

  fs.writeFileSync(path.join(sandboxPath, ".env"), envText, "utf8");
}
