import fs from "fs";
import path from "path";

export function writeWebEnv(params: {
  webPath: string;
  dbUser?: string;
  dbPass?: string;
  dbName?: string;
}) {
  const {
    webPath,
    dbUser = "startup",
    dbPass = "startup",
    dbName = "startupdb",
  } = params;

  // Inside docker network, DB hostname is "db"
  const envText =
`# Auto-generated by platform-api (Next.js + Prisma)
DATABASE_URL="postgresql://${dbUser}:${dbPass}@db:5432/${dbName}?schema=public"
`;

  fs.writeFileSync(path.join(webPath, ".env"), envText, "ascii");
}
